var TABLES = {
    SQUADS: 'squads',
    MEMBERS: 'members',
    BADGES: 'badges',
    BOTDATA: 'botdata',
    FILTERRELICCONSTRAINTS: 'filterrelicconstraints',
    FISSURES: 'fissures',
    GLOBALBLACKLIST: 'globalblacklist',
    HOSTLISTEXTRAS: 'hostlistextras',
    HOSTLISTREFINEMENTS: 'hostlistrefinements',
    HOSTLISTRELICS: 'hostlistrelics',
    HOSTLISTS: 'hostlists',
    HOSTREPUTATION: 'hostreputation',
    LEADERBOARDS: 'leaderboards',
    LINKEDRELICS: 'linkedrelics',
    MEMBERBLACKLIST: 'memberblacklist',
    MEMBERDEFAULTS: 'memberdefaults',
    MEMBERFISSURES: 'memberfissures',
    MEMBERFRIENDS: 'memberfriends',
    MEMBERRELICSUBSCRIPTIONS: 'memberrelicsubscriptions',
    MEMBERREPUTATION: 'memberreputation',
    MEMBERSERVERPING: 'memberserverping',
    MEMBERSTATUS: 'memberstatus',
    MEMBERUSERSUBSCRIPTIONS: 'memberusersubscriptions',
    OFFCYCLEFRIENDS: 'offcyclefriends',
    PINGTYPES: 'pingtypes',
    PRIMEPARTS: 'primeparts',
    PRIMESETS: 'primesets',
    RECRUITMENTCHANNELS: 'recruitmentchannels',
    RECRUITMENTFILTERS: 'recruitmentfilters',
    RECRUITMENTFILTERSACTIVE: 'recruitmentfiltersactive',
    REFINEMENT: 'refinement',
    RELICDEFAULTS: 'relicdefaults',
    RELICFRIENDS: 'relicfriends',
    RELICRELEASEINFO: 'relicreleaseinfo',
    RELICREPUTATION: 'relicreputation',
    RELICROLES: 'relicroles',
    RELICS: 'relics',
    SERVERBLACKLIST: 'serverblacklist',
    SERVERS: 'servers',
    SQUADPOSTS: 'squadposts',
    SQUADREFINEMENT: 'squadrefinement',
    SQUADRELICS: 'squadrelics',
    SQUADUSERS: 'squadusers',
    STATUS: 'status'
};

if (process.env.NODE_ENV == 'development'){
    TABLES = {
        SQUADS: 'squadstest',
        MEMBERS: 'members',
        BADGES: 'badges',
        BOTDATA: 'botdata',
        FILTERRELICCONSTRAINTS: 'filterrelicconstraints',
        FISSURES: 'fissures',
        GLOBALBLACKLIST: 'globalblacklist',
        HOSTLISTEXTRAS: 'hostlistextras',
        HOSTLISTREFINEMENTS: 'hostlistrefinements',
        HOSTLISTRELICS: 'hostlistrelics',
        HOSTLISTS: 'hostlists',
        HOSTREPUTATION: 'hostreputation',
        LEADERBOARDS: 'leaderboards',
        LINKEDRELICS: 'linkedrelics',
        MEMBERBLACKLIST: 'memberblacklist',
        MEMBERDEFAULTS: 'memberdefaults',
        MEMBERFISSURES: 'memberfissures',
        MEMBERFRIENDS: 'memberfriends',
        MEMBERRELICSUBSCRIPTIONS: 'memberrelicsubscriptions',
        MEMBERREPUTATION: 'memberreputation',
        MEMBERSERVERPING: 'memberserverping',
        MEMBERSTATUS: 'memberstatus',
        MEMBERUSERSUBSCRIPTIONS: 'memberusersubscriptions',
        OFFCYCLEFRIENDS: 'offcyclefriends',
        PINGTYPES: 'pingtypes',
        PRIMEPARTS: 'primeparts',
        PRIMESETS: 'primesets',
        RECRUITMENTCHANNELS: 'recruitmentchannels',
        RECRUITMENTFILTERS: 'recruitmentfilters',
        RECRUITMENTFILTERSACTIVE: 'recruitmentfiltersactive',
        REFINEMENT: 'refinement',
        RELICDEFAULTS: 'relicdefaults',
        RELICFRIENDS: 'relicfriends',
        RELICRELEASEINFO: 'relicreleaseinfo',
        RELICREPUTATION: 'relicreputation',
        RELICROLES: 'relicroles',
        RELICS: 'relics',
        SERVERBLACKLIST: 'serverblacklist',
        SERVERS: 'servers',
        SQUADPOSTS: 'squadposts',
        SQUADREFINEMENT: 'squadrefinement',
        SQUADRELICS: 'squadrelics',
        SQUADUSERS: 'squadusers',
        STATUS: 'status'
    }
}

export default TABLES;